SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
LINE_WIDTH = 2
# Player related constants
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 200
PLAYER_SPEED = 200
PLAYER_ACCELERATION = 400
PLAYER_DRAG = 0.98
PLAYER_SPEED_BOOST_MULTIPLIER = 1.7
PLAYER_ACCELERATION_BOOST_MULTIPLIER = 1.6
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3
PLAYER_RESPAWN_PAUSE_SECONDS = 1.5
PLAYER_SPAWN_INVULNERABILITY_SECONDS = 3.0
PLAYER_LIVES = 3
PLAYER_SCORE = 0
SHOT_RADIUS = 5

# Power-up related constants
POWERUP_RADIUS = 18
POWERUP_SPEED_DURATION_SECONDS = 12
POWERUP_SHIELD_DURATION_SECONDS = 5
POWERUP_BOMB_SCORE_INTERVAL = 6000
POWERUP_BOMB_BLAST_RADIUS_MULTIPLIER = 8
POWERUP_BOMB_BLAST_DURATION_SECONDS = 0.35
POWERUP_SPEED_SCORE_THRESHOLD = 500
POWERUP_SHIELD_SCORE_THRESHOLD = 500
POWERUP_SPEED_SPAWN_MIN_SECONDS = 10
POWERUP_SPEED_SPAWN_MAX_SECONDS = 35
POWERUP_SHIELD_SPAWN_MIN_SECONDS = 20
POWERUP_SHIELD_SPAWN_MAX_SECONDS = 45

# Asteroid related constants
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_POINTS = {
    1: 100,
    2: 50,
    3: 20
}